# Generated by Django 4.2.1 on 2023-05-29 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('type', models.CharField(default='D', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Doctor', max_length=10),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('age', models.IntegerField(default=-1)),
                ('Weight', models.FloatField(default=-1.0)),
                ('Address', models.TextField(default='NA')),
                ('Contact', models.CharField(default='NA', max_length=10)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(default=None, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
    ]
