# Generated by Django 4.2.1 on 2023-05-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_event_type_patient_event_doctor_event_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='User',
        ),
    ]
